name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test

      - name: Upload coverage to Coveralls
        if: always() # Run this step regardless of test success or failure
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          if [ -f coverage/lcov.info ]; then
            npx coveralls < coverage/lcov.info
          else
            echo "lcov.info not found, skipping Coveralls upload."
            exit 1
          fi
